# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black