name: Build

on: push

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.9"

    - name: Set plugin version environment variables
      run: |
        TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "VERSION=$(echo ${TAG} | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')-alpha" >> $GITHUB_ENV
    - name: Build package
      run: |
        python helper.py package dev-${GITHUB_SHA}
        mkdir tmp
        unzip koordinates.zip -d tmp

    - name: Save PR number to zips
      run: |
        cd tmp
        echo ${{ github.event.number }} | tee pr_number
        echo ${{ github.event.pull_request.head.sha }} | tee git_commit
        echo ${{ github.event.number }}

    - uses: actions/upload-artifact@v2
      with:
        name: koordinates_package.${{ env.VERSION }}
        path: tmp
