name: Release

on:
  push:
    tags: "*"

jobs:
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build package
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        python build.py ${GITHUB_REF##*/}

    - name: Create/update release on GitHub
      uses: ncipollo/release-action@v1.8.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        omitNameDuringUpdate: true
        artifacts: "kart-${GITHUB_REF##*/}.zip"
