name: Release

on:
  push:
    tags: ["v*"]

jobs:
  test:
    uses: koordinates/koordinates-qgis-plugin/.github/workflows/testing.yml@main

  release:
    name: "Release on tag"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Build package
        run: |
          python helper.py package "${GITHUB_REF/refs\/tags\//}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ github.repository == 'koordinates/koordinates-qgis-plugin' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            koordinates-*.zip
